[2019-04-18 18:48:23] request.INFO: Matched route "cliente_new". {"route_parameters":{"_controller":"ELE\\EditorialBundle\\Controller\\clienteController::newAction","_route":"cliente_new"},"request_uri":"http://localhost/laboratorioe/web/app.php/cliente/new"} []
[2019-04-18 18:48:23] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-04-18 18:48:23] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "portada" as such route does not exist.") in "cliente/new.html.twig" at line 70." at /var/www/html/laboratorioe/vendor/twig/twig/lib/Twig/Template.php line 182 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"portada\" as such route does not exist.\") in \"cliente/new.html.twig\" at line 70. at /var/www/html/laboratorioe/vendor/twig/twig/lib/Twig/Template.php:182, Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"portada\" as such route does not exist. at /var/www/html/laboratorioe/var/cache/prod/appProdUrlGenerator.php:74)"} []
